const apiURL = 'https://super-trivia-api.herokuapp.com/trivia'
const apiKey = 'fVvuHQrocVXC9G9z06xa3ec9rdXYGZyJZRDXJ9k3arjVxy2zuUXX6c34Z2dgnlx2'

export const UserAPI = {
    // Getting user information by username
    async getUserByUsername(username) {
        try {
            const result = await fetch(`${apiURL}?username=${username}`).then(r => r.json())
            return [null, result]
        } catch (error) {
            return [error.message, null]
        }
    },
    // Creating a new user with username input, autogenerated id and high score value 0
    async addUser(username) {
        try {
            const result = await fetch(`${apiURL}`, {
                method: 'POST',
                headers: {
                    'X-API-Key': apiKey,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ 
                    username: username, 
                    highScore: 0 
                }) 
            })
            .then(result => result.json())
            return [null, result]

        } catch (error) {
            return [error.message, null]
        }
    },
    // Updating user's high score
    async editHighScore(userId) {
        try {
            const result = await fetch(`${apiURL}/${userId}`, {
                method: 'PATCH',
                headers: {
                    'X-API-Key': apiKey,
                  'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    highScore: 100  
                })
            })
            .then(result => result.json())
            return [null, result]
        } catch (error) {
            return [error.message, null]
        }
    }
}